import { Inter } from "next/font/google";
import "./globals.css";
import { EmailProvider } from "@/context/emailcontext";
import { OtpProvider } from "@/context/otpcontext";
import { ReceiverProvider } from "@/context/receiverContext";
import { ConsumerProvider } from "@/context/consumerDetailsContext";
import { MessageStatusProvider } from "@/context/messageStatusContext";
import "bootstrap/dist/css/bootstrap.min.css";
import 'react-toastify/dist/ReactToastify.css';
import 'react-image-crop/dist/ReactCrop.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "EXAMATE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossOrigin="anonymous"/>

</head>
    
        
<body className={inter.className}>
        <OtpProvider>
          <EmailProvider>
          <ReceiverProvider>
            <ConsumerProvider>
              <MessageStatusProvider>
            <div></div>
            <div>{children}</div>
            </MessageStatusProvider>
            </ConsumerProvider>
            </ReceiverProvider>
          </EmailProvider>
        </OtpProvider>
        
      </body>
    </html>
  );
}
